"""Build 02_Application_Source/data/inventory.js from Inventory/register_counts.json.

register_counts.json holds the physical counts exactly as written in the registers
(per location, per page, in Sr. No. order) plus the item master (code, category, unit).
Run after a new physical count:  python 03_Automation_System/build_inventory_data.py
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'Inventory', 'register_counts.json')
OUT = os.path.join(ROOT, '02_Application_Source', 'data', 'inventory.js')

doc = json.load(io.open(SRC, encoding='utf-8'))
locations = [loc['name'] for loc in doc['locations']]
items = {i['code']: dict(i, opening={l: 0 for l in locations}) for i in doc['items']}
register_lists = []
for loc in doc['locations']:
    for lst in loc['lists']:
        lines = []
        for ln in lst['lines']:
            item = items[ln['code']]
            assert item['unit'] == ln['unit'], (ln, item)
            item['opening'][loc['name']] += ln['qty']
            lines.append({k: ln[k] for k in ('sr', 'code', 'qty', 'asWritten') if k in ln} | ({'note': ln['note']} if ln.get('note') else {}))
        register_lists.append({'location': loc['name'], 'title': lst['title'], 'lines': lines})

order = [i['code'] for i in doc['items']]
out_items = [items[c] for c in order]
js = f"""/**
 * HOTEL SKY 5 - INVENTORY ITEM MASTER
 * GENERATED by 03_Automation_System/build_inventory_data.py from Inventory/register_counts.json.
 * Opening stock = physical counts per location. Do not hand-edit; recount, update the JSON, re-run.
 */

export const COUNT_DATES = {json.dumps({l['name']: l['countDate'] for l in doc['locations']}, ensure_ascii=False, indent=4)};

export const LOCATIONS = Object.keys(COUNT_DATES);

// Location names used before 29-09-2026 (entries saved with them belong to the kitchen)
export const LEGACY_LOCATIONS = {{ 'Inventory Stock': '{locations[0]}', 'Crockery & Serveware': '{locations[0]}' }};

// The registers exactly as written: per location, per page, in Sr. No. order
export const registerLists = {json.dumps(register_lists, ensure_ascii=False, indent=2)};

export const inventoryItems = {json.dumps(out_items, ensure_ascii=False, indent=2)};
"""
io.open(OUT, 'w', encoding='utf-8', newline='\n').write(js)
print(f'{len(out_items)} items, {sum(len(r["lines"]) for r in register_lists)} register lines, locations: {locations}')
